name: Shotgun
version: 1.3
main: me.butkicker12.Shotgun.Shotgun
author: Butkicker12
commands:
  Airstrike:
   description: Uses the airstrike command
   usage: /airstrike
  Nuke:
   description: Uses the nuke command
   usage: /nuke
  Shotgun:
   description: Uses the shotgun command
   usage: /shotgun
permissions:
  shotgun.airstrike:
   description: Uses the airstrike command
   default: op
  shotgun.shotgun:
   description: Uses the shotgun
   default: op
  shotgun.nuke:
   description: Uses the nuke command
   default: op
  shotgun.grenade:
   description: Uses the grenade
   default: op
  shotgun.smoke:
   description: Uses the smoke grenade
   default: op