name: Shotgun
version: 1.1
main: com.thebkkingdom.Shotgun.Shotgun
commands:
  Airstrike:
   description: Help Menu
   usage: /Airstrike
  Nuke:
   description: Help Menu
   usage: /Nuke
permissions:
  shotgun.airstrike:
   description: Uses the airstrike command
   default: op
  shotgun.shotgun:
   description: Uses the shotgun
   default: op
  shotgun.nuke:
   description: Uses the nuke command
   default: op
  shotgun.grenade:
   description: Uses the grenade
   default: op
  shotgun.smoke:
   description: Uses the smoke grenade
   default: op